#!/usr/bin/env bash
# Writes the Homebrew cask and the Scoop manifest for a released version.
#
# These used to be generated by `goreleaser release`, which is no longer used
# because the open-source edition cannot package binaries it did not build. See
# the header of assemble.sh.
#
# Both files are the same idea: a small text file naming a version, the URLs to
# download, and the SHA-256 of each. The checksums come from the checksums.txt
# the release already publishes, so a manifest cannot disagree with the artifact
# it points at, which is the failure mode worth designing against: a cask whose
# hash is stale fails on the user's machine, after the download, with an error
# that reads like corruption.
#
#   scripts/release/manifests.sh <version-without-v> <release-dir> <output-dir>

set -euo pipefail

VERSION="${1:?version, without the leading v}"
RELDIR="${2:?directory holding the archives and checksums.txt}"
OUT="${3:?directory to write the manifests into}"

REPO_URL="https://github.com/291-Group/LAN-Sheriff"
BASE="$REPO_URL/releases/download/v${VERSION}"
SUMS="$RELDIR/checksums.txt"
[ -f "$SUMS" ] || { echo "no checksums.txt in $RELDIR" >&2; exit 1; }

mkdir -p "$OUT/Casks" "$OUT/bucket"

# Look a checksum up by archive name, and fail loudly if it is absent. A
# manifest naming an artifact that was not released would install nothing and
# blame the user's network.
sum_for() {
  local name="$1" v
  v=$(awk -v n="$name" '$2 == n {print $1}' "$SUMS" | head -1)
  [ -n "$v" ] || { echo "checksums.txt has no entry for $name" >&2; exit 1; }
  printf '%s' "$v"
}

BIN=lan-sheriff
mac_arm="${BIN}_${VERSION}_darwin_arm64.tar.gz"
mac_amd="${BIN}_${VERSION}_darwin_amd64.tar.gz"
win_amd="${BIN}_${VERSION}_windows_amd64.tar.gz"

# ── Homebrew, a cask rather than a formula ───────────────────────────────────
#
# A cask because the release ships a pre-built binary; a formula would be for
# something Homebrew compiles. It is also why this is macOS only: Homebrew on
# Linux does not install casks, and Linux has the .deb, .rpm, .apk and
# install.sh instead.
#
# Not maskable, not notarised: the post-install hook strips the quarantine
# attribute macOS puts on anything downloaded, because without it the first run
# is refused by Gatekeeper with a dialog claiming the binary is damaged. It is
# not damaged, it is unsigned, and somebody who deliberately tapped this
# repository has already made that decision.
cat > "$OUT/Casks/lan-sheriff.rb" <<RUBY
cask "lan-sheriff" do
  version "${VERSION}"

  on_arm do
    sha256 "$(sum_for "$mac_arm")"
    url "${BASE}/${mac_arm}"
  end
  on_intel do
    sha256 "$(sum_for "$mac_amd")"
    url "${BASE}/${mac_amd}"
  end

  name "LAN Sheriff"
  desc "Self-hosted network monitor: watch what leaves, map where it goes, flag what does not belong"
  homepage "${REPO_URL}"

  binary "lan-sheriff"

  postflight do
    # Unsigned, so macOS quarantines it and Gatekeeper reports it as damaged.
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/lan-sheriff"],
                   must_succeed: false
  end

  # Uninstalling leaves the database alone; \`brew uninstall --zap\` removes it.
  # A monitor that erased months of history because somebody changed how it was
  # installed would be a poor neighbour.
  zap trash: "~/Library/Application Support/lan-sheriff"

  caveats <<~EOS
    Start it with:
      lan-sheriff

    Deputy Mode needs no privileges and works immediately: it names the
    application behind every connection this machine makes.

    Patrol Mode sees other devices and DNS, and needs access to the BPF
    devices, which in practice means:
      sudo lan-sheriff

    Seeing other devices also needs a vantage point. A machine plugged into a
    switch sees its own traffic and broadcast, and nothing else:
      ${REPO_URL}/blob/main/docs/VANTAGE-POINTS.md
  EOS
end
RUBY

# ── Scoop, for Windows ───────────────────────────────────────────────────────
#
# Npcap is named and not bundled: its licence forbids redistribution. The
# binary runs without it in Deputy Mode and says which mode it is in, so the
# note is guidance rather than a prerequisite.
cat > "$OUT/bucket/lan-sheriff.json" <<JSON
{
    "version": "${VERSION}",
    "description": "Self-hosted network monitor: watch what leaves, map where it goes, flag what does not belong",
    "homepage": "${REPO_URL}",
    "license": "AGPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "${BASE}/${win_amd}",
            "hash": "$(sum_for "$win_amd")"
        }
    },
    "bin": "lan-sheriff.exe",
    "notes": [
        "Deputy Mode works now and needs no privileges.",
        "Patrol Mode additionally needs Npcap, from https://npcap.com , which cannot be bundled because its licence forbids redistribution.",
        "Seeing other devices also needs a vantage point: ${REPO_URL}/blob/main/docs/VANTAGE-POINTS.md",
        "Start it with: lan-sheriff"
    ],
    "checkver": {
        "github": "${REPO_URL}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "${REPO_URL}/releases/download/v\$version/${BIN}_\$version_windows_amd64.tar.gz"
            }
        }
    }
}
JSON

echo "  wrote Casks/lan-sheriff.rb and bucket/lan-sheriff.json for ${VERSION}"
