// Command mkicons renders the LAN Sheriff badge to PNG at the sizes browsers
// and phones actually ask for.
//
// # Why this exists rather than a build-time SVG converter
//
// An SVG favicon covers modern browsers, and it is what the dashboard links
// first. Two things still need raster: Safari before 16, and the iOS home
// screen, which will not accept an SVG at all and falls back to a screenshot
// of the page if no PNG is offered.
//
// Every obvious way to produce those PNGs was worse. A rasteriser like
// librsvg or ImageMagick is a build dependency for four small files. Driving a
// headless browser is a build dependency with a browser inside it. Committing
// PNGs somebody generated by hand once is how icons drift from the logo they
// are supposed to be.
//
// The badge is a star, five lines and six circles. That is arithmetic, and the
// standard library can do arithmetic, so this draws it directly with 4x
// supersampling for the edges. No dependencies, runs anywhere Go runs, and the
// output is identical every time.
//
// **The geometry is duplicated from web/public/badge.svg and web/src/badge.tsx
// on purpose, and that is the one thing to watch.** Three copies of the same
// shape can drift. They are all derived from the constants below; if the badge
// changes, change it here and re-run, and the test in this package compares
// the two coordinate sets so a drift fails rather than ships.
//
//	go run ./scripts/mkicons
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/png"
	"log"
	"math"
	"os"
	"path/filepath"
)

// The badge, in the 64x64 space the SVG uses.
const (
	viewBox = 64.0
	cx, cy  = 32.0, 32.0

	starStroke = 2.4
	linkStroke = 1.5
	nodeR      = 2.2
	hubR       = 4.6
	hubStroke  = 1.8
)

// star is the ten-point path: alternating outer and inner vertices.
var star = [][2]float64{
	{32, 4}, {39.41, 21.81}, {58.63, 23.35}, {43.98, 35.89}, {48.46, 54.65},
	{32, 44.6}, {15.54, 54.65}, {20.02, 35.89}, {5.37, 23.35}, {24.59, 21.81},
}

// nodes are where the network sits inside the badge: one per star point.
var nodes = [][2]float64{
	{32, 12.5}, {50.55, 25.97}, {43.46, 47.78}, {20.54, 47.78}, {13.45, 25.97},
}

var (
	faceTop = color.NRGBA{0xf2, 0xc3, 0x57, 0xff}
	faceBot = color.NRGBA{0xd9, 0xa2, 0x27, 0xff}
	edge    = color.NRGBA{0xb0, 0x7f, 0x16, 0xff}
	link    = color.NRGBA{0x78, 0x52, 0x08, 0x80}
	nodeCol = color.NRGBA{0x7d, 0x58, 0x06, 0xff}
	hubFill = color.NRGBA{0xff, 0xf3, 0xd4, 0xff}
)

func main() {
	out := "web/public"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}
	for _, size := range []int{32, 180, 192, 512} {
		name := filepath.Join(out, fmt.Sprintf("icon-%d.png", size))
		if err := write(name, size); err != nil {
			log.Fatalf("mkicons: %v", err)
		}
		fmt.Printf("wrote %s\n", name)
	}
}

func write(name string, size int) error {
	img := render(size)
	f, err := os.Create(name)
	if err != nil {
		return err
	}
	defer f.Close()
	return png.Encode(f, img)
}

// ss is the supersampling factor. Four samples per axis is sixteen per pixel,
// which is enough to keep the star's points from looking chewed at 32px, and
// cheap enough that the largest icon renders in well under a second.
const ss = 4

func render(size int) *image.NRGBA {
	hi := size * ss
	scale := float64(hi) / viewBox
	acc := image.NewNRGBA(image.Rect(0, 0, hi, hi))

	for y := 0; y < hi; y++ {
		for x := 0; x < hi; x++ {
			// Sample at the pixel centre, in badge coordinates.
			px, py := (float64(x)+0.5)/scale, (float64(y)+0.5)/scale
			acc.SetNRGBA(x, y, sample(px, py))
		}
	}
	return downsample(acc, size)
}

// sample decides the colour of one point, painting back to front exactly as
// the SVG does: star face, star edge, links, nodes, hub.
func sample(x, y float64) color.NRGBA {
	var out color.NRGBA

	if inPolygon(x, y, star) {
		// The SVG fills with a vertical gradient; interpolate the same way.
		t := clamp01(y / viewBox)
		out = lerp(faceTop, faceBot, t)
	}
	if distToPath(x, y, star) <= starStroke/2 {
		out = over(out, edge)
	}
	for _, n := range nodes {
		if distToSegment(x, y, cx, cy, n[0], n[1]) <= linkStroke/2 {
			out = over(out, link)
		}
	}
	for _, n := range nodes {
		if math.Hypot(x-n[0], y-n[1]) <= nodeR {
			out = over(out, nodeCol)
		}
	}
	if d := math.Hypot(x-cx, y-cy); d <= hubR+hubStroke/2 {
		if d <= hubR-hubStroke/2 {
			out = over(out, hubFill)
		} else {
			out = over(out, edge)
		}
	}
	return out
}

func downsample(src *image.NRGBA, size int) *image.NRGBA {
	dst := image.NewNRGBA(image.Rect(0, 0, size, size))
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			var r, g, b, a int
			for dy := 0; dy < ss; dy++ {
				for dx := 0; dx < ss; dx++ {
					c := src.NRGBAAt(x*ss+dx, y*ss+dy)
					// Weight colour by coverage so transparent samples do not
					// drag the edges toward black.
					r += int(c.R) * int(c.A) / 255
					g += int(c.G) * int(c.A) / 255
					b += int(c.B) * int(c.A) / 255
					a += int(c.A)
				}
			}
			n := ss * ss
			alpha := a / n
			if alpha == 0 {
				dst.SetNRGBA(x, y, color.NRGBA{})
				continue
			}
			// Undo the coverage weighting to recover the colour.
			dst.SetNRGBA(x, y, color.NRGBA{
				R: uint8(clampi(r * 255 / n / alpha)),
				G: uint8(clampi(g * 255 / n / alpha)),
				B: uint8(clampi(b * 255 / n / alpha)),
				A: uint8(alpha),
			})
		}
	}
	return dst
}

// ---------- geometry ----------

func inPolygon(x, y float64, poly [][2]float64) bool {
	in := false
	for i, j := 0, len(poly)-1; i < len(poly); j, i = i, i+1 {
		xi, yi := poly[i][0], poly[i][1]
		xj, yj := poly[j][0], poly[j][1]
		if (yi > y) != (yj > y) && x < (xj-xi)*(y-yi)/(yj-yi)+xi {
			in = !in
		}
	}
	return in
}

func distToPath(x, y float64, poly [][2]float64) float64 {
	best := math.MaxFloat64
	for i, j := 0, len(poly)-1; i < len(poly); j, i = i, i+1 {
		if d := distToSegment(x, y, poly[j][0], poly[j][1], poly[i][0], poly[i][1]); d < best {
			best = d
		}
	}
	return best
}

func distToSegment(px, py, ax, ay, bx, by float64) float64 {
	dx, dy := bx-ax, by-ay
	if dx == 0 && dy == 0 {
		return math.Hypot(px-ax, py-ay)
	}
	t := clamp01(((px-ax)*dx + (py-ay)*dy) / (dx*dx + dy*dy))
	return math.Hypot(px-(ax+t*dx), py-(ay+t*dy))
}

// ---------- colour ----------

func over(dst, src color.NRGBA) color.NRGBA {
	if src.A == 255 {
		return src
	}
	sa := float64(src.A) / 255
	da := float64(dst.A) / 255
	oa := sa + da*(1-sa)
	if oa == 0 {
		return color.NRGBA{}
	}
	mix := func(s, d uint8) uint8 {
		return uint8((float64(s)*sa + float64(d)*da*(1-sa)) / oa)
	}
	return color.NRGBA{mix(src.R, dst.R), mix(src.G, dst.G), mix(src.B, dst.B), uint8(oa * 255)}
}

func lerp(a, b color.NRGBA, t float64) color.NRGBA {
	m := func(x, y uint8) uint8 { return uint8(float64(x) + (float64(y)-float64(x))*t) }
	return color.NRGBA{m(a.R, b.R), m(a.G, b.G), m(a.B, b.B), 255}
}

func clamp01(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}

func clampi(v int) int {
	if v < 0 {
		return 0
	}
	if v > 255 {
		return 255
	}
	return v
}
