//go:build linux

package cli

import (
	"os"
	"strings"
	"testing"
)

// The unit this writes to /etc/systemd/system is generated by string
// concatenation, which is fine right up until a value contains a newline or a
// flag is renamed and nothing notices until systemd refuses to load it on a
// user's machine.
//
// The generated file has also been checked with `systemd-analyze verify`,
// which is the only thing that actually knows whether systemd will accept it.
// Set GEN_UNIT to a path to write it out and do that again.
func TestSystemdUnit(t *testing.T) {
	cfg := installConfig{
		Listen:  "127.0.0.1:2911",
		DataDir: "/var/lib/lan-sheriff",
		BinPath: "/usr/local/bin/lan-sheriff",
	}
	u := systemdUnit(cfg)

	for _, want := range []string{
		"ExecStart=" + cfg.BinPath,
		"--listen " + cfg.Listen,
		"--data-dir " + cfg.DataDir,
		"User=" + serviceUser,
		// Capture privilege comes from the unit, never from file capabilities.
		"AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN",
		// PrivateDevices must stay off or the packet socket disappears.
		"PrivateDevices=no",
		"[Install]",
	} {
		if !strings.Contains(u, want) {
			t.Errorf("unit is missing %q", want)
		}
	}

	if strings.Contains(u, "PrivateDevices=yes") {
		t.Error("PrivateDevices=yes removes the packet socket capture needs")
	}

	if path := os.Getenv("GEN_UNIT"); path != "" {
		if err := os.WriteFile(path, []byte(u), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// The dashboard URL is what the installer prints at the end, and it is the one
// line a first-time user acts on. A bare wildcard address is not somewhere a
// browser can go.
func TestDashboardURL(t *testing.T) {
	if got := dashboardURL("127.0.0.1:2911"); got != "http://127.0.0.1:2911" {
		t.Errorf("localhost: got %q", got)
	}
	if got := dashboardURL("0.0.0.0:2911"); strings.Contains(got, "0.0.0.0") {
		t.Errorf("wildcard should not be offered as a link: %q", got)
	}
}
